Translate french ok
MonitorControl/MonitorControl pull request #611
Opened 2021-09-21 06:38 UTC by yoan8306

2021-09-21 09:39 UTC, waydabber commented
Hi @the0neyouseek - can you have a look at this one? Yesterday there is a different one and since I don't speak French I can't decide on this. Thank you! :)

2021-09-21 10:23 UTC, the0neyouseek requested changes
I've left some comments (in French) if you can, have a look. Otherwise, everything looks good to me

2021-09-21 10:23 UTC, the0neyouseek commented on MonitorControl/Support/fr.lproj/Localizable.strings
> -"Shift was pressed during launch. MonitorControl started in safe mode. Default preferences are reloaded, DDC read is blocked." = "Maj. appuyée pendant le démarrage. MonitorControl démarré en mode san
Cette traduction est plus logique. L'application a déjà démarré

2021-09-21 10:23 UTC, the0neyouseek commented on MonitorControl/UI/fr.lproj/Main.strings
> +"bkM-Px-U3b.title" = "Désactive le volume OSD";
Plutôt "Désactive l'OSD de volume macOS"

2021-09-21 10:23 UTC, the0neyouseek commented on MonitorControl/UI/fr.lproj/Main.strings
> +"bZq-0d-lJa.title" = "Active Mute commande DDC";
Active la commande DDC "Muet" (ou "Sourdine" ?)

2021-09-21 10:23 UTC, the0neyouseek commented on MonitorControl/UI/fr.lproj/Main.strings
> +"Cle-DD-vR7.title" = "Personnaliser";
Personnalisé

2021-09-21 19:19 UTC, yoan8306 commented
Hi, 
my answer in  green below.
Thanks :)
Regards


> Le 21 sept. 2021 à 12:23, Guillaume B. ***@***.***> a écrit :
> 
> 
> @the0neyouseek requested changes on this pull request.
> 
> I've left some comments (in French) if you can, have a look. Otherwise, everything looks good to me
> 
> In MonitorControl/Support/fr.lproj/Localizable.strings <https://github.com/MonitorControl/MonitorControl/pull/611#discussion_r712898145>:
> 
> >  
>  /* Shown in the alert dialog */
>  "Safe Mode Activated" = "Mode sans échec activé";
>  
>  /* Shown in the alert dialog */
> -"Shift was pressed during launch. MonitorControl started in safe mode. Default preferences are reloaded, DDC read is blocked." = « Maintenir Maj. appuyée pendant le démarrage. MonitorControl démarré en mode sans échec. Les préférences par défaut sont utilisées, la communication via DDC est bloquée.";
> Cette traduction est plus logique. L'application a déjà démarré // it’s wrong. 
> 
> In MonitorControl/UI/fr.lproj/Main.strings <https://github.com/MonitorControl/MonitorControl/pull/611#discussion_r712899257>:
> 
> >  
>  /* Class = "NSButtonCell"; title = "Disable macOS volume OSD"; ObjectID = "bkM-Px-U3b"; */
> -"bkM-Px-U3b.title" = "Disable macOS volume OSD";
> +"bkM-Px-U3b.title" = "Désactive le volume OSD";
> Plutôt "Désactive l'OSD de volume macOS » //OK  good
> 
> In MonitorControl/UI/fr.lproj/Main.strings <https://github.com/MonitorControl/MonitorControl/pull/611#discussion_r712901000>:
> 
> >  
>  /* Class = "NSButtonCell"; title = "Enable Mute DDC command"; ObjectID = "bZq-0d-lJa"; */
> -"bZq-0d-lJa.title" = "Enable Mute DDC command";
> +"bZq-0d-lJa.title" = "Active Mute commande DDC";
> Active la commande DDC "Muet" (ou "Sourdine" ?) // Active la commande DDC sourdine
> 
> In MonitorControl/UI/fr.lproj/Main.strings <https://github.com/MonitorControl/MonitorControl/pull/611#discussion_r712901952>:
> 
> >  
>  /* Class = "NSMenuItem"; title = "Custom"; ObjectID = "Cle-DD-vR7"; */
> -"Cle-DD-vR7.title" = "Custom";
> +"Cle-DD-vR7.title" = "Personnaliser";
> Personnalisé // ok
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/MonitorControl/MonitorControl/pull/611#pullrequestreview-759557643>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AIKOM7GPIUP6ZYAAN2KMCADUDBMJTANCNFSM5ENTY22A>.
>

2021-09-22 12:01 UTC, yoan8306 commented on MonitorControl/UI/fr.lproj/Main.strings
> +"bZq-0d-lJa.title" = "Active Mute commande DDC";
"Active la commande DDC sourdine"

2021-09-22 12:03 UTC, yoan8306 commented on MonitorControl/Support/fr.lproj/Localizable.strings
> -"Shift was pressed during launch. MonitorControl started in safe mode. Default preferences are reloaded, DDC read is blocked." = "Maj. appuyée pendant le démarrage. MonitorControl démarré en mode san
Maintenir Maj. appuyé pendant le démarrage.

2021-09-22 12:07 UTC, closed without merging